import sys,os
from src.constants import *

DATASET_PATH = os.path.join(ROOT_DIR,DATA_DIR,DATA_DIR_KEY)

RAW_FILE_PATH = os.path.join(ROOT_DIR, ARTIFACT_DIR, DATA_INGESTION_DIR, CURRENT_TIMESTAMP, RAW_DATA_DIR, RAW_DATA_DIR_KEY)

TRAIN_FILE_PATH = os.path.join(ROOT_DIR, ARTIFACT_DIR, DATA_INGESTION_DIR, CURRENT_TIMESTAMP, INGESTED_DATA_DIR, 
                               TRAIN_DATA_DIR_KEY)

TEST_FILE_PATH = os.path.join(ROOT_DIR, ARTIFACT_DIR, DATA_INGESTION_DIR, CURRENT_TIMESTAMP, INGESTED_DATA_DIR, 
                               TEST_DATA_DIR_KEY)

#data transformation

PREPROCESSING_OBJ_FILEPATH = os.path.join(ROOT_DIR, ARTIFACT_DIR, TRANSFORMATION_ARTIFACT_DIR, DATA_PREPROCESSED_DIR,
                                          OBJ_PREPROCESSED)

TRANSFORM_TRAIN_FILEPATH = os.path.join(ROOT_DIR, ARTIFACT_DIR, TRANSFORMATION_ARTIFACT_DIR, TRANSFORM_DIR , 
                               TRANSFORM_TRAIN_DIR_KEY)

TRANSFORM_TEST_FILEPATH = os.path.join(ROOT_DIR, ARTIFACT_DIR, TRANSFORMATION_ARTIFACT_DIR, TRANSFORM_DIR , 
                               TRANSFORM_TEST_DIR_KEY)

FE_OBJ_FILEPATH = os.path.join(ROOT_DIR, ARTIFACT_DIR, TRANSFORMATION_ARTIFACT_DIR, DATA_PREPROCESSED_DIR,
                               'fe.pkl')

#MODEL TRAINING

MODEL_FILEPATH = os.path.join(ROOT_DIR, ARTIFACT_DIR, MODEL_DIR, MODEL_OBJECT)